output:
  directory: "custom"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  path: "./files/ornament.obj"
  scale: [10.0, 10.0, 10.0]
  location: [0, 0, 0]
  rotation: [0, 0, 0]
  override_materials: false
  bevel:
    width: 0.05
    segments: 4
    profile: 0.5
  material:
    metallic: 1.0
    roughness: 0.0
    specular: 1.0

environment:
  hdri_path: "assets/christmas.exr"

camera:
  num_images: 300
  theta_min_deg: 45
  theta_max_deg: 120
  phi_start_deg: 0
  phi_end_deg: 60
  distance: 27.0
  
  trajectory_type: "plus"
  look_at: "center"
  
  plane_distance: 150.0
  plane_normal: [1, 0, 0]
  
  diamond_size: 5.0

  plus_horizontal_length: 250.0
  plus_vertical_length: 250.0
  
  trajectory_offset: [0, 0, 0]
  
  zigzag_width: 7.0
  zigzag_height: 7.0

