output:
  directory: "output"
  format: "PNG"
  resolution: [1024, 1024]
  samples: 128

blender_obj:
  spacing: 2.7         
  items:
    - path: "./files/coca-cola/coca-cola.obj"
      scale: [1.0, 1.0, 1.0]    
      location: [ 0, 0, 0 ]  
      rotation: [90, 0, 0]
      override_materials: false  
      bevel:
        width: 0.01
        segments: 2
        profile: 0.5
      material:
        metallic:        1.0
        roughness:       0.0
        specular:        1.0

    - path: "./files/coca-cola/coca-cola.obj"
      scale: [1.0, 1.0, 1.0]     
      location: [ 0, 0, 0 ]  
      rotation: [90, 0, 0]
      override_materials: false  
      bevel:
        width: 0.01
        segments: 2
        profile: 0.5
      material:
        metallic:        1.0
        roughness:       0.0
        specular:        1.0

environment:
  hdri_path: "assets/suburb.exr"

camera:
  num_images:     300
  theta_min_deg:  0
  theta_max_deg:  85
  phi_start_deg:  0
  phi_end_deg:    360
  distance:       10
  focal_length:   55
  
  trajectory_type: "golden_spiral"
  
  plane_distance: 2.0
  diamond_size: 1.0
  zigzag_width: 1.0
  zigzag_height: 1.0