output:
  directory: "output"
  format: "PNG"
  resolution: [1024, 1024]
  samples: 128

blender_obj:
  spacing: 25.0          
  items:
    - path: "./files/venus.obj"
      scale: [1.0, 1.0, 1.0]    
      base_location: [ 0, 0, 0 ]  
      rotation: [0, 0, 0]
      override_materials: false  
      bevel:
        width: 0.01
        segments: 2
        profile: 0.5
      material:
        metallic:        1.0    # full metal
        roughness:       0.0    # zero roughness = perfect mirror
        specular:        1.0

    - path: "./files/Zeus_300k_ZR.obj"
      scale: [1.0, 1.0, 1.0]     
      base_location: [ 0, 0, -5 ]  
      rotation: [0, 0, 0]
      override_materials: true  
      bevel:
        width: 0.01
        segments: 2
        profile: 0.5
      material:
        metallic:        1.0
        roughness:       0.0
        specular:        1.0

environment:
  hdri_path: "assets/outdoor.exr"

camera:
  num_images:     1500
  theta_min_deg:  0
  theta_max_deg:  85
  distance:       120
  focal_length:   55