output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  spacing: 1.5           
  items:
    - path: "./files/cola.obj"
      scale: [0.8, 0.8, 0.8]          
      base_location: [ 0, 0, 0 ]  
      rotation: [90, 0, 0]
      override_materials: false  
      bevel:
        width: 0.01
        segments: 2
        profile: 0.5
      material:
        metallic: 0.0
        roughness: 0.0
        specular: 1.0

    - path: "./files/egg.obj"
      scale: [0.3, 0.3, 0.3]       
      base_location: [ 0, 0, -1.2 ]  
      rotation: [0, 0, 0]
      override_materials: false  
      bevel:
        width: 0.005
        segments: 2
        profile: 0.3
      material:
        metallic: 0.8
        roughness: 0.2
        specular: 0.4

environment:
  hdri_path: "assets/paris.exr"

camera:
  num_images:     300
  theta_max_deg:  85       
  distance:       10.0       
  focal_length:   55