output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  path: "./files/cola.obj"
  scale: [50.0, 50.0, 50.0]
  location: [0, 0, 0]
  rotation: [90, 0, 0]  
  override_materials: true
  bevel:
    width: 0.01
    segments: 2
    profile: 0.5
  material:
    metallic: 0.8
    roughness: 0.02
    specular: 1.0

environment:
  hdri_path: "assets/paris.exr"

camera:
  num_images: 300
  theta_min_deg: 5
  theta_max_deg: 85
  distance: 250