output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  path: "./files/cola.obj"
  scale: [1.0, 1.0, 1.0]    
  location: [0, 0, 0]
  rotation: [90, 0, 0]  
  override_materials: false
  bevel:
    width: 0.01
    segments: 2
    profile: 0.5
  material:
    metallic: 0.8
    roughness: 0.02
    specular: 1.0

environment:
  hdri_path: "assets/bedroom.exr"

camera:
  num_images: 9
  theta_min_deg: 25
  theta_max_deg: 85
  phi_start_deg: 0
  phi_end_deg: 360
  distance: 7.0
  
  trajectory_type: "zigzag"
  
  plane_distance: 2.0
  diamond_size: 1.0
  zigzag_width: 7.0
  zigzag_height: 7.0