output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  path: "./files/body.obj"
  scale: [1.0, 1.0, 1.0]
  location: [0, 0, -40]
  bevel:
    width: 0.02
    segments: 3
    profile: 0.5
  material:
    metallic: 1.0
    roughness: 0.1
    specular: 0.5

environment:
  hdri_path: "assets/paris.exr"

camera:
  num_images: 9
  theta_max_deg: 85
  distance: 20.0