output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

blender_obj:
  path: "./files/egg.obj"
  scale: [0.5, 0.5, 0.5]
  location: [0, 0, 0]
  rotation: [0, 0, 0]  
  bevel:
    width: 0.02
    segments: 3
    profile: 0.5
  material:
    metallic: 1.0
    roughness: 0.1
    specular: 0.5

environment:
  hdri_path: "assets/paris.exr"

camera:
  num_images: 300
  theta_max_deg: 85
  distance: 10.0